{% set name = "jinja_partials" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/jinja_partials-{{ version }}.tar.gz
  sha256: 0c53d6e6489617a7efd403506040d5be7a138b95b7051e727cd8f42b0d8159a2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - jinja2

test:
  imports:
    - jinja_partials
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mikeckennedy/jinja_partials
  summary: Simple reuse of partial HTML page templates in the Jinja template language for Python web frameworks.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Colelyman
